title: DJC Docs
description: Scripts, commands, onliners and general sysadmin stuff
theme: just-the-docs

url: https://docs.aikedejongste.nl
ga_tracking: G-FYZXW9XYER
aux_links:
  About me: https://www.aikedejongste.nl
