title: DJC Docs
description: Scripts, commands, onliners and general sysadmin stuff
theme: just-the-docs

url: https://docs.aikedejongste.nl

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
